version: '3.8'

#Ебучая сетка с которй я больше всего страдал
networks:
  Inet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/24

services:

#Короче, ебаный рот, эта хуйня проксирует трафик от клиента к нужному серверу)
  infraredProxy:
    image: ghcr.io/haveachin/infrared:2.0.0-alpha.14
    container_name: infrared
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
      - "9090:9090"
    networks:
      Inet:
        ipv4_address: 172.18.0.2
    volumes:
      - "./ProxyConf:/infrared/"
    expose:
      - "25565"
    environment:
      INFRARED_CONFIG_PATH: "./infrared/"

#Это сервер #1
  allTheMods8:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
      CF_FILENAME_MATCHER: "1.0.22"
      MEMORY: 8G
    networks:
      Inet:
        ipv4_address: 172.18.0.3
    volumes:
      - ./allTheMods8:/data
      - ../downloads:/downloads
    restart: unless-stopped

##Это сервер #2
#  Vanilla:
#    image: itzg/minecraft-server
#    container_name: paper
#    environment:
#      EULA: "true"
#      TYPE: PAPER
#      VIEW_DISTANCE: 14
#      MEMORY: 4G
#    networks:
#      Inet:
#        ipv4_address: 172.18.0.4
#    volumes:
#      - ./Vanilla:/data
#    restart: unless-stopped

#Это сервер #3
  edickServer:
    image: itzg/minecraft-server
    container_name: edickServer
    environment:
      EULA: "TRUE"
      TYPE: MOHIST
      VERSION: 1.16.5
    networks:
      Inet:
        ipv4_address: 172.18.0.5
    volumes:
      - ./edickServer:/data
    restart: unless-stopped